quarkus:
  datasource:
    devservices:
      enabled: true
    db-kind: postgresql
    username: quarkus
    password: quarkus
    db-name: meta
    store:
      devservices:
        enabled: true
      db-kind: postgresql
      username: quarkus
      password: quarkus
      db-name: store

  liquibase:
    schemas: public
    change-log: db/meta/migrate.xml
    migrate-at-start: true
## Currently we do not have any redshift migrations, for safety lets leave this explicitly unconfigured
#    store:
#      schemas: public
#      change-log: db/store/migrate.xml
#      migrate-at-start: true
